# Generated by Django 2.2.6 on 2019-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.ImageField(upload_to='img'),
        ),
    ]
