# Generated by Django 2.2.6 on 2019-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fotografia', models.ImageField(upload_to='static/img')),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
