# Generated by Django 2.2.6 on 2019-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20191103_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.ImageField(upload_to='static/base/img'),
        ),
    ]
