# Generated by Django 3.0.5 on 2020-07-17 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AspNetRole',
            fields=[
                ('id', models.CharField(max_length=450, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('normalized_name', models.CharField(blank=True, max_length=256, null=True)),
                ('concurrency_stamp', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'asp_net_role',
            },
        ),
        migrations.CreateModel(
            name='AspNetUser',
            fields=[
                ('id', models.CharField(max_length=450, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('normalized_user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('normalized_email', models.CharField(blank=True, max_length=256, null=True)),
                ('email_confirmed', models.BooleanField()),
                ('password_hash', models.CharField(blank=True, max_length=2000, null=True)),
                ('security_stamp', models.CharField(blank=True, max_length=2000, null=True)),
                ('concurrency_stamp', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone_number_confirmed', models.BooleanField()),
                ('two_factor_enabled', models.BooleanField()),
                ('lockout_end', models.DateTimeField(blank=True, null=True)),
                ('lockout_enabled', models.BooleanField()),
                ('access_failed_count', models.IntegerField()),
            ],
            options={
                'db_table': 'asp_net_user',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creado_el', models.DateField()),
                ('terminado_el', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boleta',
            },
        ),
        migrations.CreateModel(
            name='Contacto_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('asunto', models.CharField(blank=True, max_length=45, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacto_form',
                'db_table': 'contacto_form',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creado_el', models.DateField()),
                ('total_producto', models.BigIntegerField(blank=True, null=True)),
                ('total_servicio', models.BigIntegerField()),
                ('es_aceptada', models.CharField(max_length=1)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Boleta')),
            ],
            options={
                'db_table': 'cotizacion',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'dia',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='EfMigrationHistory',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('product_version', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'ef_migration_history',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_servicio',
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('titulo_normalizado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'familia_producto',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.CharField(max_length=20)),
                ('hora_termino', models.CharField(max_length=20)),
                ('box', models.BigIntegerField()),
                ('disponible', models.CharField(max_length=1)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Dia')),
            ],
            options={
                'db_table': 'modulo',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('solicitado_el', models.DateTimeField()),
                ('actualizado_el', models.DateTimeField()),
                ('fue_recepcionado', models.BooleanField()),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('titulo_normalizado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('stock_critico', models.BigIntegerField()),
                ('es_promocion', models.CharField(max_length=1)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('esta_inactivo', models.BooleanField()),
                ('file_id', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iniciado_el', models.DateField(blank=True, null=True)),
                ('realizado_el', models.DateField(blank=True, null=True)),
                ('es_principal', models.CharField(max_length=1)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Boleta')),
                ('estado_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.EstadoServicio')),
            ],
            options={
                'db_table': 'registro_servicio',
            },
        ),
        migrations.CreateModel(
            name='RolOrden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rol_orden',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rubro',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('titulo_normalizado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=2000)),
                ('precio', models.BigIntegerField()),
                ('esta_inactivo', models.CharField(max_length=1)),
                ('es_promocion', models.CharField(max_length=1)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('file_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Suscribir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletin', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suscribir',
                'db_table': 'suscribir',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fono_fijo', models.CharField(blank=True, max_length=8, null=True)),
                ('fono_movil', models.CharField(blank=True, max_length=8, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_foto', models.ImageField(blank=True, default='foto_perfil/default.png', upload_to='foto_perfil')),
                ('creado_el', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True, null=True)),
                ('es_extranjero', models.BooleanField()),
                ('comuna_id', models.BigIntegerField()),
                ('genero_id', models.BigIntegerField()),
                ('asp_net_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='generales.AspNetUser')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='generales.EstadoCivil')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioOrden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registrado_el', models.DateField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Orden')),
                ('rol_orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.RolOrden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario')),
            ],
            options={
                'db_table': 'usuario_orden',
            },
        ),
        migrations.CreateModel(
            name='UsoProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_prevista', models.BigIntegerField()),
                ('sub_total_previsto', models.BigIntegerField()),
                ('cantidad_real', models.BigIntegerField(blank=True, null=True)),
                ('sub_total_real', models.BigIntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Producto')),
                ('registro_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.RegistroServicio')),
            ],
            options={
                'db_table': 'uso_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('titulo_normalizado', models.CharField(max_length=50)),
                ('familia_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.FamiliaProducto')),
            ],
            options={
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('solicitado_el', models.DateTimeField(auto_now_add=True, null=True)),
                ('fue_anulada', models.CharField(max_length=1)),
                ('fecha_reserva', models.DateField()),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('hora', models.CharField(max_length=20)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='RelServicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Servicio')),
                ('servicio_id2', models.ForeignKey(db_column='servicio_id2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_2', to='generales.Servicio')),
            ],
            options={
                'db_table': 'rel_servicio',
            },
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Servicio'),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_normalizado', models.CharField(max_length=50)),
                ('fono_fijo', models.CharField(max_length=8)),
                ('fono_movil', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('esta_inactivo', models.BooleanField()),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Rubro')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Servicio')),
            ],
            options={
                'db_table': 'producto_servicio',
            },
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('sub_total', models.BigIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Producto')),
            ],
            options={
                'db_table': 'producto_orden',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.TipoProducto'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pagado_el', models.DateField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Cotizacion')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.MetodoPago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Servicio'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario'),
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(upload_to='documentos')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario')),
            ],
            options={
                'db_table': 'documento_cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('fono_movil', models.CharField(max_length=8)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Proveedor')),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Region')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Usuario'),
        ),
        migrations.CreateModel(
            name='AspNetUserClaim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('claim_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.AspNetUser')),
            ],
            options={
                'db_table': 'asp_net_user_claim',
            },
        ),
        migrations.CreateModel(
            name='AspNetRoleClaim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('claim_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.AspNetRole')),
            ],
            options={
                'db_table': 'asp_net_role_claim',
            },
        ),
        migrations.CreateModel(
            name='AspNetUserToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='generales.AspNetUser')),
                ('login_provider', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'asp_net_user_token',
                'unique_together': {('user', 'login_provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AspNetUserLogin',
            fields=[
                ('login_provider', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=128)),
                ('provider_display_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.AspNetUser')),
            ],
            options={
                'db_table': 'asp_net_user_login',
                'unique_together': {('login_provider', 'provider_key')},
            },
        ),
        migrations.CreateModel(
            name='AspNetUserRole',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='generales.AspNetUser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generales.AspNetRole')),
            ],
            options={
                'db_table': 'asp_net_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
